### ISSUE TITLE
代码基本都跑不通，作者也不修改，书还在继续卖，什么情况呀

### ISSUE THREAD

**Issue by usouc** [chenzomi12/deeplearning-inaction#4]
前面章节的代码跑不通，后面比如第七章，居然不提供数据集？不知道作者啥意思，也不说

**Comment by chenzomi12** [comment]
尊敬的读者您好，

前面章节的代码在ipython中都能跑得通，也给出对应的输出。请尊敬的读者仔细核对。
至于您说的第7章节的数据集问题，数据集并不在代码中，可以通过下载公共数据集作为example。后续会根据您宝贵的意见提供网络下载链接。
